apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  selector:
    matchLabels:
      app: prediction
  replicas: 1
  template:
    metadata:
      labels:
        app: prediction
    spec:
     containers:
     - name: prediction
       image: firaslam/breast-cancer-detection:1.0    
       ports:
       - containerPort: 5000





      
  
  
    