apiVersion: v1
kind: Service
metadata:
  name: prediction-service-cloud
  labels:
    app: prediction
spec:
  selector:
    app: prediction
  ports:
    - name: http
      port: 5000

  type: LoadBalancer