apiVersion: v1
kind: Service
metadata:
  name: prediction-service-edge
  # labels:
  #   app: prediction
spec:
  selector:
    app: prediction
  ports:
    - name: http
      port: 5000
      nodePort: 30090
  
  type: NodePort
